### ISSUE TITLE
Performance problem when counting number of days between two PlainDate

### ISSUE THREAD

**Issue by jsarson** [MenoData/Time4J#317]
I have a performance problem when using time4j on Android. Please check my code. Can I do it better?

```
PlainDate today = SystemClock.inLocalView().today();
PlainDate endDate = TemporalType.JAVA_UTIL_DATE.translate(date).toLocalTimestamp().getCalendarDate();
long days = net.time4j.CalendarUnit.DAYS.between(today, endDate);
```

First call takes about 1,5s, another call is quick - about 0-1 ms.

Thank you!

**Comment by MenoData** [comment]
Two questions: 

- What is your configuration? Do you use this time the extra tz-repository of Time4J?
- Do you execute the code the first time after starting the application? If so then I get the suspicion this might be due to loading timezone data in the background (the methods `SystemClock.inLocalView()` or `Moment.toLocalTimestamp()` need to load timezone data).

All other things should be very quick so I cannot imagine any other performance issue (even quicker than in Java-8 ;-).) Originally I had written Time4J not primarily for Android. Maybe the timezone issue is related to the internal usage of `ClassLoader.getResourceAsStream()`. Well, I will probably refactor the resource loading infrastructure anyway - keeping the situation on Android in mind.

**Comment by jsarson** [comment]
I made another try with clean project and following code:
```
long durationInMillis = 1000000;
long start = System.currentTimeMillis();

Duration<?> dur = Duration.of(durationInMillis, ClockUnit.MILLIS).with(Duration.STD_CLOCK_PERIOD).with(ClockUnit.SECONDS.truncated());
Log.e("TIME4JTEST", PrettyTime.of(new Locale("en")).print(dur, TextWidth.WIDE));

long end = System.currentTimeMillis();
Log.e("TIME4JTEST", String.valueOf(end - start));
```

1a) with configuration 
```
compile 'net.time4j:time4j-android:3.4'
compile 'net.time4j:time4j-core:3.4'
compile 'net.time4j:time4j-i18n:3.4'
compile 'net.time4j:time4j-olson:3.4'
compile 'net.time4j:time4j-tzdata:1.4-2015e'
```
takes about 700ms for the first time.

1b) with configuration 
```
compile 'net.time4j:time4j-android:3.4'
compile 'net.time4j:time4j-core:3.4'
compile 'net.time4j:time4j-i18n:3.4'
```

takes about 300-400ms for the first time.

2) I try both. There is nothing different. I made a workaround and run time4j formating code in different thread right after the app starts (just for speedup another call).

**Comment by MenoData** [comment]
Thanks for your feedback. Your workaround sounds reasonable. About your benchmark: I would rather use `System.nanoTime()`. Anyway, I agree that the initialization times up to 1.5 seconds you observed appear too much.

I cannot promise an immediate solution but will tackle it in the week after my summer holidays (after 26th of July). At least I see two areas of optimization. One thing is the issue #320 which might be included in next release v3.5. The other harder thing is refactoring of the resource loader infrastructure to workaround a bug in Android which I need some time for. This bug affects time zone data as well as i18n-resources. The basic idea behind refactoring would be to load resources via URLConnection using `setUseCaches(false)` as Google has recommended (provided that the resource URLs are available on Android). See also these links:

- https://android.googlesource.com/platform/libcore/+/05a5c2f89e12e27db69f24165a05bdfd0476c73a
- https://code.google.com/p/android/issues/detail?id=60071

**Comment by MenoData** [comment]
I could now identify another problem caused by an excessive operator cache in the underlying element framework of Time4J. A sensible refactoring is possible for next release v3.5/4.3.

**Comment by MenoData** [comment]
Well, now the optimization of class initialization is done. However, profiler tests have revealed that the class initialization of Time4J was not so bad (rather good). The main problem is just resource and class loading - also due to the multi-jar-architecture. For example, I have just profiled the class initialization of `PlainDate` using VisualVM on a standard Oracle-VM:

![plaindateprofile_full](https://cloud.githubusercontent.com/assets/3025695/8689942/8422cad8-2aae-11e5-9b9e-d0cd48b8d750.png)

I have now two actions in mind:

- Introducing a new class `ResourceLoader` which will be at least useful for loading (text)-resources and helps to workaround a known Android-problem (see also https://code.google.com/p/android/issues/detail?id=60071).
- Releasing a specialized single-jar-edition of Time4J based on level-6-branch (eventuall in two variants, compact and full).

**Comment by MenoData** [comment]
I have now released the new project Time4A. Details see issue #326 and on GitHub:

https://github.com/MenoData/Time4A

There you will also find a section how to use the new AAR-library. Keep in mind that - compared with v3.4 - you have to change following things:

- Change your dependencies: Remove all Time4J-modules, even the core. The new artifact `time4j-android` with the version v3.5-2015f replaces all Time4J-modules with the exception of "misc" and "range". If you  need those two modules you can continue to use it.

- Adjust the initialization of your application as shown on the GitHub-page of Time4A.

The source code of Time4A is just a copy of the version v3.5 of Time4J (level6-branch), but organizes the text resources, calendar data and timezone data in a different way using the assets-directory of your Android-app. You can even override the data by defining your application assets (using the same resource paths and syntax). The classifier 2015f remembers of the version of the timezone data in use. Please also note that Time4J itself will stop to run on Android platform starting with v3.5 so you must use Time4A from now on.

Using the new AAR-library will solve this issue because I have tested this new approach against a (slightly modified) copy of Time4J-v3.5 and observed a **reduction of start-up-time of about 50%**.

By the way: A prefetch-initialization using a separate thread is still possible and a good idea in general. Maybe I should enhance Time4A with such an optional prefetch-method in the next release v3.6.
