### ISSUE TITLE
HijriCalendar variant

### ISSUE THREAD

**Issue by discovererer** [MenoData/Time4J#407]
ChronoFormatter<HijriCalendar> formatter2 =
				ChronoFormatter.setUp(HijriCalendar.class, Locale.ENGLISH)
						.addPattern("EEE, d. MMMM yy", PatternType.NON_ISO_DATE).build()
						.with(Attributes.PIVOT_YEAR, 1500);

		PlainDate today2 = PlainDate.of(735914, EpochDays.RATA_DIE);
		HijriCalendar h = today2.transform(HijriCalendar.class, "islamic-fatimida");// also islamic-habashalhasiba

		String s = formatter2.format(h);

		//EpochDays
		//735913 : Wed, 30. Muharram 37
		//735914 : java.lang.IllegalArgumentException: Invalid hijri date: year=1437, month=1, day=31
		//735915 : Fri, 2. Safar 37

**Comment by MenoData** [comment]
That is a terrible bug around year/month-boundaries. Thanks for pointing it out.

**Comment by MenoData** [comment]
The bugfix release will be published as soon as possible. All variants in `HijriAlgorithm` are affected (but not Umalqura etc.). The new tests cover a whole year including two year boundaries and 11 month boundaries - and also your example.

Side note:

Instead of ```today2.transform(HijriCalendar.class, "islamic-fatimida")```,
you can also write ```today2.transform(HijriCalendar.class, HijriAlgorithm.FATIMID_ASTRO)```. Latter one is equivalent but a) makes clearer which class is here relevant and b) defends better against typos.
