### ISSUE TITLE
Time4A - Is there any way to use Time4A from service class?

### ISSUE THREAD

**Issue by bahrulhikmi** [MenoData/Time4J#454]
Hi,
Great library.

But I cannot find a way to pass "Application" to the initializer from service class.
ApplicationStarter.initialize(this);

Is there any workaround to be able to use the library from a non-activity class?

Thanks

**Comment by MenoData** [comment]
Sorry, actually not but I have looked at the source code and seen that it would be probably sufficient to pass an object of type `Content` (not yet tested) - see http://developer.android.com/reference/android/content/Context.html 

It is used for accessing the asset resources and for determining if Android uses 24-hour-clock in user preferences or not.

Would a new method using such a parameter instead of `android.app.Application` satisfy you? If yes then I would deprecate the old methods in favour of the new more general methods. Two methods in class `ApplicationStarter` are then affected:

- public static void initialize(Application application)
- public static void prepareResources(Application application)

**Comment by discovererer** [comment]
its work for me
ApplicationStarter.initialize(getApplication());

**Comment by bahrulhikmi** [comment]
Yeah, nevermind :) , just realized that we actually can get Application from service!
Thanks.
