### ISSUE TITLE
Support year

### ISSUE THREAD

**Issue by preuss** [MenoData/Time4J#555]
It would be nice if Time4j could support a Year class.
So I could parse to a year, and don't have any month or day.
Example:
```
ChronoFormatter<PlainYear> style = ChronoFormatter.ofYearPattern("yyyy", PatternType.CLDR, Locale.US);
String year = "2016";
PlainYear year = style.parse(year);
```

**Comment by MenoData** [comment]
A class only using the proleptic ISO-8601-year already exists if you also have the range-module. 

Example:

```java
CalendarYear year = 
  ChronoFormatter.ofPattern(
    "yyyy", PatternType.CLDR, Locale.ROOT, CalendarYear.chronology()
  ).parse("2016")
```

The `ChronoFormatter` can process this way every type which is compatible to `ChronoEntity`. However, I have located the class `CalendarYear` in the range-module because I believe that

a) many people have less need for parsing years because of simple alternatives like `Integer.parseInt("2016")`
b) enhancing the `CalendarYear`-class by interval features makes it more useful. Iterating every day over a year is very easy in this case (for-each-loop or similar)

**Comment by MenoData** [comment]
For general styled parsing, see also the [javadoc.](http://time4j.net/javadoc-en/net/time4j/range/CalendarYear.html#YEAR)
