### ISSUE TITLE
Timestamp representation of a Moment in TAI and UTC are inconsistent?

### ISSUE THREAD

**Issue by passchieri** [MenoData/Time4J#606]
If I compare the timestamp representation of a Moment in TAI and in UTC via

`Moment moment=SystemClock.currentMoment();`
`long diff=moment.transform(TimeScale.TAI).longValue()-moment.transform(TimeScale.UTC).longValue()` 

I always get the value of 10. I would expect that this would depend on the number of leap seconds that have been inserted before that moment, so currently (25-1-2017) I would expect 37.

Do I misinterprete the values returned by `transform`, or is this a bug?

**Comment by MenoData** [comment]
Thanks for the good and interesting question. It is not a bug but intentional behaviour. However, the documentation should probably be improved to explain the behaviour of method [transform(TimeScale)](http://time4j.net/javadoc-en/net/time4j/Moment.html#transform-net.time4j.scale.TimeScale-) and to show how you can get the desired effect to observe the delta between UTC and TAI .

First we have to consider that TWO ways exist how to describe a timestamp.

a) We can consider a moment as count of elapsed seconds since an epoch defined by a time scale and then compare the number values. The internal state of `Moment` represents this model on scale UTC. This way is also realized by the method `transform(TimeScale)`.

b) Alternatively we can format a `Moment` for example in the ISO-notation of "uuuu-MM-dd'T'HH:mm:ss.fffffffffXXX" and then compare the time representations. This way is realized by the method `toString(TimeScale)` (in a slightly different format which is mostly suitable for debugging or demo  purposes). Most external URLs uses this model to describe the delta between TAI and UTC, for example: http://www.leapsecond.com/java/gpsclock.htm

If we go the first way then the given time scale defines how to determine the epoch reference and how to count the elapsed seconds. In case of TAI see this excerpt from documentation in class `TimeScale`:

> At the calendar date 1972-01-01 the difference between TAI and UTC was defined as exactly 10 seconds (TAI = UTC + 10). This difference is fixed for all timestamps in epoch seconds because both TAI and UTC counts in pure SI-seconds. But note: If TAI and UTC are resolved to an element-oriented notation (YYYY-MM-DD HH:MM:SS) then the difference between TAI and UTC increases with every inserted leap second because of the different labelling.

So what does this mean for the observed delta between TAI and UTC?

The chosen reference points (epochs) for TAI and UTC are such that there is a difference of 10 seconds. Furthermore and most important to understand: Both scales are atomic scales meaning that these scales count SI-seconds continuously in the view of elapsed SI-seconds since UTC-epoch (1972). Leap seconds are not suppressed, neither by UTC (trivial) nor by TAI (which considers leap seconds as normal SI-seconds like other SI-seconds, too and does not simply stop the clock counter). The logical conclusion here is: **If no SI-second is suppressed in counting then the delta between TAI and UTC cannot change in this model.**

However, in the view of representation timestamps, UTC and TAI handle leap seconds very different.

UTC labels the leap seconds with the special value "60" causing a discontinuity while TAI just changes the (TAI-)day to next one.

A possible enhancement for the documentation of method `transform(TimeScale)` might be:

> Represents this timestamp as decimal value in given time scale.  The scale determines the epoch reference to be used and how to count elapsed seconds since a given epoch. Please note that some scales like TAI, GPS and UTC are atomic scales counting SI-seconds continuously. Such time scales do not suppress leap seconds in this view. However, the scales handle the representation of leap seconds in a very different way. TAI for example does not consider leap seconds as leap seconds but just normal seconds (in the model of 1 TAI-day = 86400 SI-seconds) while UTC lables leap seconds with the special value 60 causing discontinuities.

Do you have an alternative suggestion for a clearer documentation? Personally I would also add a link to the method [toString(TimeScale)](http://time4j.net/javadoc-en/net/time4j/Moment.html#toString-net.time4j.scale.TimeScale-) which directly demonstrates the delta between the different scales (what you obviously like to see).

I also plan to add a new format attribute specifying a time scale to be used in formatting or parsing, see issue #607

**Comment by MenoData** [comment]
About the concrete numbers you gave: Until now 27 leap seconds have been added. Together with the original arbitrarily chosen offset of 10 seconds between TAI and UTC, this sums up to 37 seconds. You can see this difference if using `toString(TimeScale)`.

**Comment by passchieri** [comment]
Thanks for the clear and detailed explanation. I understand the reasoning and it sounds like a consistent approach. However, I am working on cooperative intelligent transport systems, where in the ETSI standards it has been decided to make use of TAI timestamps as the basis for all time information. This was chosen to eliminate the effects of jumps due to leap seconds. But from your line of reasoning, which I agree with, it would not make a difference whether UTC or TAI is used for that.

Furthermore, for implementation it is currently assumed that the conversion from system time in UTC and timestamps in TAI, the leap seconds have to be taken into account. That indicates that the assumption is then that the UTC timestamps do make a jump at a leap seconds, whereas the TAI timestamp does not. Anyway, I now understand what I get from the library, and how that relates to what is expected in C-ITS.

I think your proposed document changes are okay: they make it explicit how the different  timescales relate to each other.

**Comment by MenoData** [comment]
Now I have released v4.24 which contains special format and parsing support for time scales. I have also updated the tutorial where you can read the [new page](http://time4j.net/tutorial/timescales.html) about the most important details of time scale support in Time4J.
