### ISSUE TITLE
Question: delivery time

### ISSUE THREAD

**Issue by discovererer** [MenoData/Time4J#718]
hi, is it be possible to get the moment of delivery of the new year in solar calendar like PersianCalendar?

**Comment by MenoData** [comment]
Do you mean expressions like `PersianCalendar cal = PersianCalendar.of(persianYear, 1, 1)`?

Or, if you start with the gregorian calendar today, then you could write:

```
PersianCalendar cal =
  PlainDate.nowInSystemTime().transform(PersianCalendar.axis()).with(PersianCalendar.DAY_OF_YEAR, 1);
```

The last expression could also be simplified by:

```
PersianCalendar cal =
  PersianCalendar.nowInSystemTime().with(PersianCalendar.DAY_OF_YEAR.minimized());
```

Using static imports will further shorten the code (here: static import for DAY_OF_YEAR).

Or do you talk about something quite different?

**Comment by MenoData** [comment]
If you want to translate any Persian calendar to a `Moment` then you need a clock time and a timezone as usual:

```
PersianCalendar cal = ...; // maybe an expression for New Year like above
Moment m = cal.atTime(14, 45).in(Timezone.of("Asia/Teheran"), StartOfDay.MIDNIGHT);
```

**Comment by MenoData** [comment]
After some rethinking, determining the first moment of a calendar year (non-gregorian) should not force the user to specify a clock time. While this is okay for the gregorian calendar (users just choose midnight) where a possible timezone shift like in Brazil is still taken into account, this becomes difficult if the start of calendar day deviates from midnight and is associated to events like sunset.

Therefore I have following enhancement in mind for all `Calendrical` or `CalendarVariant`-classes to make user life easier:

`public Moment at(StartOfDay, Timezone)`

What do you think?

**Comment by discovererer** [comment]
Thank you for answering
I mean the moment of March equinox  on Earth. that is the beginning of the solar year. it may not be on the first day of the year

for example: 
March Equinox in UTC, Time Zone is on Tuesday, 20 March 2018, 16:15 UTC

https://en.wikipedia.org/wiki/Equinox
https://www.timeanddate.com/calendar/march-equinox.html

**Comment by MenoData** [comment]
Thanks for the clarification of your question. If you are just interested in the moment of the astronomical event of vernal equinox (on northern hemisphere) then you can simply write:

```
    System.out.println(AstronomicalSeason.VERNAL_EQUINOX.inYear(2018));

    PersianCalendar pcal = PersianCalendar.of(1397, PersianMonth.FARVARDIN, 1); // new year
    System.out.println(
        AstronomicalSeason.VERNAL_EQUINOX.inYear(
                pcal.get(CommonElements.RELATED_GREGORIAN_YEAR)));
```

Both lines produce the same result - either if you specify the gregorian year (2018) or construct a Persian calendar date:

> 2018-03-20T16:15:07,454302310Z

However, it should be noted that this moment is not exactly the same as the moment of the begin of Persian calendar year because latter one follows the midnight-to-midnight cycle while the astronomical event can happen on any time of day. So my idea about 

`public Moment atFirstMoment(StartOfDay, TZID)` 

is still different from a pure astronomical view.

**Comment by discovererer** [comment]
Yes
That's the answer, Thanks for everything

Note: In the official documents of the Iranian calendar, the time of the vernal equinox is different in a few seconds, I think the calculations are different
```
1396-12-30T19:45:07
1396-12-30T19:45:28 // In the official documents of the Iranian calendar
```

**Comment by MenoData** [comment]
As described in the API-documentation, too:

> The precision is for modern times (around 2000) better than a minute. The underlying astronomical calculations are based on formula given by Jean Meeus in his book &quot;Astronomical algorithms&quot;. 

Concretely: I used chapter 27 and the best available data for delta-T-correction. Who knows which algorithm the official documents of the Iranian calendar use? So I cannot say what is more precise. I recommend as best practice for most astronomical calculations to round the results to minutes.

**Comment by MenoData** [comment]
Wait a minute, the persian date 1396-12-30 does not exist because that year is not a leap year so the esfand-month has only 29 days. That means: 1396-12-29 (originating from the astronomical vernal equinox calculation) is followed by 1397-01-01. And this is correct because the moment of equinox is AFTER noon in Teheran so the Persian calendar chooses the next day as New Year.

**Comment by discovererer** [comment]
sorry, Typo mistake
I edited it
