### ISSUE TITLE
persianCalendar.getMaximum(PersianCalendar.WEEKDAY_IN_MONTH) return wrong value

### ISSUE THREAD

**Issue by mohamadk** [MenoData/Time4J#737]
this method returns wrong value for example weeks in 1396/10 is 6 which this method return 5.
persianCalendar.getMaximum(PersianCalendar.WEEKDAY_IN_MONTH)

**Comment by MenoData** [comment]
Hm, I don't see a bug, see thexe examples:

    PersianCalendar date = PersianCalendar.nowInSystemTime();
    System.out.println(date); // AP-1396-10-25 (DEY with length of 30 days)
    System.out.println(date.getDayOfWeek()); // Monday
    System.out.println(date.getMaximum(PersianCalendar.WEEKDAY_IN_MONTH)); // 4 Mondays in Dey

    date = PersianCalendar.of(1396, PersianMonth.DEY, 1);
    System.out.println(date.getDayOfWeek()); // Friday
    System.out.println(date.getMaximum(PersianCalendar.WEEKDAY_IN_MONTH)); // 5 Fridays in Dey

**About the meaning of "WEEKDAY_IN_MONTH":** It depends on the current day-of-week and the length of month. Since the 10th month of Persian calendar, Dey, has only 30 days, it will never be possible to get 6 weekdays in the same month. I suspect that you might have misinterpreted the meaning of this element.

Maybe the[ bounded week-of-month](http://time4j.net/javadoc-en/net/time4j/Weekmodel.html#boundedWeekOfMonth--) is what you want. Indeed, that definition of week can have 6 as maximum but is only supported for ISO-8601 (PlainDate), not for `PersianCalendar`. Would be a request for enhancement.

Until now, there is only the normal [week-of-month](http://time4j.net/javadoc-en/net/time4j/calendar/CommonElements.html#weekOfMonth-net.time4j.engine.Chronology-net.time4j.Weekmodel-). The element can be obtained by an expression like `CommonElements.weekOfMonth(PersianCalendar.axis(), PersianCalendar.getDefaultWeekmodel())`. However, keep in mind that this week is never truncated, meaning that the last day of DEY-month belongs to the first week of next month. Probably not what you want.

**Comment by MenoData** [comment]
I have created a new issue #738 which hopefully addresses what you really want. About using "WEEKDAY_IN_MONTH", I don't see any bug so closing this issue. Thanks for your feedback. It is welcome. I am also open to any suggestions for improvement of documentation or what so ever, for example in the new issue about bounded week-of-month which cuts weeks at month boundaries.

**Comment by MenoData** [comment]
The next release of Time4J would enable following code (I suspect that you wan this):

`PersianCalendar.of(1396, 10, 4).getMaximum(PersianCalendar.BOUNDED_WEEK_OF_MONTH) // 6`
