### ISSUE TITLE
Throwing ArithmeticException in Coptic/Ethiopian transform

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#791]
**Example:**
```
CalendarSystem<CopticCalendar> calsys = CopticCalendar.axis().getCalendarSystem();
try {
    calsys.transform(3651704528L);
    System.out.println("No Exception");
} catch (IllegalArgumentException iae) {
    System.out.println("IllegalArgumentException");
} catch (ArithmeticException ae) {
    System.out.println("ArithmeticException");
}
```
Version: 4.38
Output: "ArithmeticException"
Expected output: "IllegalArgumentException"

**Comment by MenoData** [comment]
Time4J has two types of exceptions which are not documented in every method:

- `NullPointerException` when passing null-parameters (unless explicitly stated otherwise)
- `ArithmeticException` in case of numeric overflow (usually indicates an out-of-range-situation)

So I see this rather as a documentation issue. My suggestion: I add some documentation for example on package-level, the overview page of javadoc and on the read.me-page here on GitHub. What do you think?

By the way, your value is really far beyond the supported maximum:

`System.out.println("max=" + calsys.getMaximumSinceUTC()); // 3035846L
`

**Comment by iamcalendar** [comment]
Thanks for explanation.

Though we agree with you about `NullPointerException` as it is a well-known practice to not document it, we were not aware of `ArithmeticException` not being documented until you told so. We believe adding documents as you suggested may reduce confusion; however, for increasing compatibility with other libraries (for example, https://docs.oracle.com/javase/8/docs/api/java/time/chrono/ChronoLocalDate.html) we think it would be better to include `ArithmeticException` in method's description.

Regarding this particular `transform` function, don't you think users are expecting `IllegalArgumentException` if the argument is out of range as clearly stated in the document no matter how far it is beyond the range? Could you please kindly let us know if this can be the case for other methods in the library? Thanks!

**Comment by MenoData** [comment]
I will see how much I can mention the `ArithmeticException` but I am not sure if I can catch every possible occurrence because it is deeply involved in all calendrical calculations. At least I will document it extra in all changing methods (mostly with prefix "with").

**Comment by MenoData** [comment]
Okay, all with...()-methods in the abstract class `ChronoEntity` are already documented as possibly throwing an `ArithmeticException` so I leave it for now here. If you find more undocumented occurrences of `ArithmeticException` then you can open a new issue, otherwise your reported problem is fixed in next release.
