### ISSUE TITLE
Wrong calculation in ThaiSolarCalendar

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#796]
Example:
```
ThaiSolarCalendar date = ThaiSolarCalendar.ofBuddhist(2482, 12, 31);
System.out.println(date.plus(CalendarDays.ONE));
```
Version: 4.38
Output: BUDDHIST-2482-01-01
Expected output: BUDDHIST-2483-04-01

**Comment by MenoData** [comment]
Your expectation is (surpringly for most people) wrong. The Thai solar calendar has one historic anomaly in year counting and the synchronization of year cycle with month cycle. Before gregorian year 1941, the buddhist year started on first of April, NOT in January. It is still trivial that first of January follows directly after end of December, but the buddhist year still remains the same (here: 2482) because it is not yet April.

FYI, the gregorian year 1940 was the last one which started in April (and then ended in December instead of March - an extra short year).

**Comment by iamcalendar** [comment]
Thank you very much for your help and support! You are right.
