### ISSUE TITLE
Invalid Hispanic display name

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#809]
In the following snippet we try to display Hispanic name in English:
```
for (TextWidth textWidth : TextWidth.values()) {
    System.out.print(textWidth + ": ");
    System.out.println(HistoricEra.HISPANIC.getDisplayName(Locale.ENGLISH, textWidth));
}
```
Output:
```
WIDE: Era de César
ABBREVIATED: Era
SHORT: Era
NARROW: Era
```
As shown in the output, the display name in` WIDE` width is in different language than English. In addition, in other width formats the display name (`Era`) is generic and doesn't seem to have Hispanic meaning.

**Comment by MenoData** [comment]
This is an internationalization issue with the background that the wide-known CLDR repository has no resources for this purpose (so we have to collect it ourselves). Until now I have just assumed that Spanish and Latin might be the relevant languages which need to be supported. But I agree, English is also important here (and French and ...).

Actual resource links:

- [Latin](https://github.com/MenoData/Time4J/blob/master/base/src/main/resources/names/historic_la.properties)
- [Spanish](https://github.com/MenoData/Time4J/blob/master/base/src/main/resources/names/iso8601.properties)

Latter one is even the fallback. It is probably not only for you strange that the abbreviation is just "Era", but historically the Spanics have really used that word for their special era in midage. According to the [English Wikipedia page](https://en.wikipedia.org/wiki/Spanish_era), I suggest to support English in the following way:

"era of Caesar"

The same page also shows the historical use like: "Era CMXLI" (=941) for "anno domini 903". However, the English abbreviation should be the same as the full form in order to reduce confusion for English speakers.

**Comment by iamcalendar** [comment]
Thanks!

**Comment by MenoData** [comment]
I have changed the capitalization of English forms and also discovered a small bug in the narrow forms which always fell back to abbreviated forms because the text resource files are not complete for some historic eras.
