### ISSUE TITLE
EastAsianCalendar cannot operate on time units smaller than a day.

### ISSUE THREAD

**Issue by Charlweed** [MenoData/Time4J#810]
I was trying to use the plus method on ChineseCalendar to add a number of seconds, and there does not seem to be any way. At least not in 4.99-beta.
ChineseCalendar.Unit  ChineseCalendar.Unit has no unit smaller than DAYS. None of the arithmetic methods will accept any argument types except ChineseCalendar.Unit, and there is no way to convert other units into  ChineseCalendar.Unit. This effectually blocks any operations with ClockUnit on units of time smaller than an day.
I'm hacking around on the source to see what happens when I insert hours-minutes-seconds into the ChineseCalendar.Unit enum, but it is unclear why there are different incompatible types for:

net.time4j.CalendarUnit
net.time4j.ClockUnit
net.time4j.calendar.ChineseCalendar.Unit

and no ChineseCalendar ClockUnit at all.

**Comment by MenoData** [comment]
In general, the units associated with calendars have no finer granularity than days because calendars itself don't bother about clock time. Calendars are not designed for this purpose.

But you can combine calendars with clock time to a [general timestamp](http://time4j.net/javadoc-en/net/time4j/GeneralTimestamp.html) for example the following way:

`GeneralTimestamp<ChineseCalendar> tsp = chineseCalendar.atTime(19, 45);`

There is also a more general `at(PlainTime)`-method available. Once you have a general timestamp, you can either extract the calendar component or the (iso) clock time, or you can convert it to a `Moment` (with specifying the timezone and the start of day).

Two special calendars also have special time units via extension classes:

- EthiopianTime
- HebrewTime

Historically, Chinese people (and other East Asian peoples, too) had also used other time units which are not compatible with western clock units, but this has not (yet?) been implemented in Time4J.

**Comment by MenoData** [comment]
By the way, the type `CalendarUnit` only handles ISO-calendar units where the month-based units are totally different from the Chinese month units. We should not mix both units in order to guarantee minimum compile-time type safety.

**Comment by MenoData** [comment]
About time arithmetic with plus()- or minus()-methods, this has not (yet?) been implemented in the class `GeneralTimestamp` but you can of course convert your calendar to a `Moment` and then apply time arithmetic in the physical space.

**Comment by Charlweed** [comment]
Thank you!

Perhaps I will try that approach.

Dev

**Comment by MenoData** [comment]
As you see, I have added another example above which demonstrates how to realize addition of time units on a Chinese calendar. I am not sure however, if an extra method in the class `GeneralTimestamp` is worth the effort because the signature of such a method has also to accept two extra parameters for the time zone and maybe even the start of day if deviating from the calendar standard. Feel free to make suggestions for either such a method or instead more documentation.

**Comment by MenoData** [comment]
Okay, I have now added some time arithmetic to the class `GeneralTimestamp` directly for convenience. But if you want clock units in physical space (taking time zones into account) then please follow my advise to first convert to `Moment`.
