### ISSUE TITLE
Limit pretty time output to specific units

### ISSUE THREAD

**Issue by kashike** [MenoData/Time4J#846]
I'm currently doing something along the lines of `PrettyTime.of(Locale.ENGLISH).print(Duration.between(start, end))`
which, in some cases, results in things like `10 hours and 9 microseconds`.

Is it possible to get `PrettyTime` to *not* print units that I give it (an exclusion list)? I'd like to be able to just get `10 hours`.

**Comment by MenoData** [comment]
The normalization you want is easily possible but not with `net.time4j.PrettyTime`, instead one step earlier. **Reason: The responsibility of `PrettyTime` is just printing but not normalization which is a manipulation feature of durations.**

There are many ways of normalization. It mainly depends on which kind of duration you use.

a) using `java.time.Duration`
--------------------------------

The example code you presented in your question tells me that you probably try to print a duration of type `java.time.Duration` because Time4J does not know a between-method directly present on `net.time4j.Duration`. The duration type built into `java.time` is not so flexible that you can simply specify any arbitrary set of units but since Java 9 you can [truncate a duration](https://docs.oracle.com/javase/9/docs/api/java/time/Duration.html#truncatedTo-java.time.temporal.TemporalUnit-). Example for a duration in minute precision:

```String s = 
  PrettyTime.of(Locale.ENGLISH).print(
    java.time.Duration.between(start, end).truncatedTo(ChronoUnit.MINUTES));
```

b) using Time4J
------------------

The primary duration type is here `net.time4j.Duration` which allows more normalization methods. I don't know what your start- and end-variables are but I assume that you try to handle timestamps/times of type `LocalDateTime` or `LocalTime`. The Time4J-equivalents would be: `PlainTimestamp` or `PlainTime`. You can call the conversion `PlainTimestamp.from(localDateTime)` or `PlainTime.from(localTime)`.

As mentioned earlier, `net.time4j.Duration` does not (immediately) know a between-method but the construction of a `TimeMetric` as factory for a duration [by any set of duration units](http://time4j.net/javadoc-en/net/time4j/Duration.html#in-U...-) and then calling `between(...)`. Example:
```
  private static final IsoUnit DAYS = CalendarUnit.DAYS;
  private static final IsoUnit HOURS = ClockUnit.HOURS;
  private static final IsoUnit MINUTES = ClockUnit.MINUTES;

  PlainTimestamp start = PlainTimestamp.of(2014, 3, 28, 0, 30);
  PlainTimestamp end = PlainTimestamp.of(2014, 4, 5, 14, 15);
  net.time4j.Duration<IsoUnit> duration =
      net.time4j.Duration.in(DAYS, HOURS, MINUTES).between(start, end);
  System.out.println(duration); // output: P8DT13H45M
  String s = PrettyTime.of(Locale.ENGLISH).print(duration);
```
There are also other more specific methods to create a `TimeMetric` like `inClockUnits()` or `inYearsMonthsDays()` (for pure calendric durations only). Furthermore: There is a general normalization method [with(Normalizer)](http://time4j.net/javadoc-en/net/time4j/Duration.html#with-net.time4j.engine.Normalizer-). Example for a duration in clock units:

```
  LocalTime start = ...;
  LocalTime end = ...;

  net.time4j.Duration<ClockUnit> timePeriod = 
    net.time4j.Duration.inClockUnits().between(PlainTime.from(start), PlainTime.from(end));
  System.out.println(timePeriod.with(ClockUnit.MINUTES.rounded()));
  // output: P4H57M 
  String s = PrettyTime.of(Locale.ENGLISH).print(timePeriod);
```

Other normalization methods like `clockunit.only()` or `clockUnit.truncated()` (as the equivalent to Java 9-method) are also available. More documentation can also be found in the [tutorial](http://time4j.net/tutorial/duration.html).

**Comment by kashike** [comment]
In my case, `start` and `end` are `java.time.Instant` instances - your (a) solution is what I wanted, I just didn't expect that method name in `java.time.Duration`.

Thanks!

**Comment by MenoData** [comment]
Okay, but some remarks should be noted about your solution:

a) the method `truncatedTo(...)` only exists from Java-9 onwards, so `withNanos(0)` or similar would be the workaround to be used in Java-8,

b) units like years, months or weeks cannot be printed,

c) using `java.time.Duration` in `PrettyTime` indirectly involves a [conversion](http://time4j.net/javadoc-en/net/time4j/TemporalType.html#THREETEN_DURATION) with automatic normalization. Furthermore, but not obvious: The conversion happens at fixed offset `ZonalOffset.UTC` while the Time4J-solution allows any timezone to be deployed which can cause a difference around daylight-saving-switches.

**Demonstration for the different capabilities of both duration classes:**

        Instant start = Moment.UNIX_EPOCH.toTemporalAccessor();
        Instant end = Instant.now();

        // your solution
        String s = 
                PrettyTime.of(Locale.ENGLISH).print(
                        java.time.Duration.between(start, end).withNanos(0));
        System.out.println(s); // 17887 days, 4 hours, 35 minutes, and 33 seconds

        // solution with greatest flexibility
        Duration<?> d =
            Duration.in(
                Timezone.ofSystem(),
                CalendarUnit.YEARS, CalendarUnit.MONTHS, CalendarUnit.WEEKS, CalendarUnit.DAYS,
                ClockUnit.HOURS, ClockUnit.MINUTES, ClockUnit.SECONDS
            ).between(Moment.from(start).toLocalTimestamp(), Moment.from(end).toLocalTimestamp());
        String s2 = PrettyTime.of(Locale.ENGLISH).print(d);
        System.out.println(s2); // 48 years, 11 months, 3 weeks, 4 hours, 35 minutes, and 33 seconds
