### ISSUE TITLE
Time4A - Performance 1st launch time

### ISSUE THREAD

**Issue by kingvhit** [MenoData/Time4J#876]
Hi @MenoData , 
Thank you for all of the awesome things you do in Time4A library. 
I'm beginning to use your Time4A in my project. 
All of working well, and then I want to optimize the performance of my app, the problems occur when we first open the app. It takes more than 1300ms for the first launch, and around 287ms ~ 350ms for second and later launch.

I check the performance of all method and I found the method `PlainDate.nowInSystemTime()` take more than 350ms in the first launch.
 
What are the problems here, Please let me know? My English skill still is not good, please ask me again if you did not understand what I want. 

Thank you.

**Comment by MenoData** [comment]
The expression `PlainDate.nowInSystemTime()` does not only load the class `PlainDate` on first usage but also loads time zone related classes and resources. Such zone rules and resources are unavoidably complex and need some time when first used.

And loading the system time zone is necessary for determining the actual calendar date.

As you can see in your time measurements, Time4A does caching whenever possible so reusage is less time-consuming. However, the times are also device-dependent so I cannot say so much about the absolute values you observed. But maybe you have not used the background-loading on the very first initialization of Time4A. This special feature can be used by following setup:

```
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ApplicationStarter.initialize(this, true); // with prefetch on background thread
        // do some other things like opening a splash screen or welcome message
    }
}
```

Maybe you have suppressed the prefetch. If you allow it (setting the boolean parameter to `true`) then your app could show an opening splash screen while loading some data in the background.

**Comment by MenoData** [comment]
Another option would be to use the platform zone data of your device. If so then you could replace the expression `PlainDate.nowInSystemTime()` by

`SystemClock.inPlatformView().today()`

See also the [API-documentation](http://time4j.net/javadoc-en/net/time4j/SystemClock.html#inPlatformView--).

**Comment by kingvhit** [comment]
Thank you for a quick reply,

I have been added `ApplicationStarter.initialize(this, true)` in Application class before and try to do all of your suggestion in this post and nothing improves.

So I tried another way with PlainDate by the method:
```
val today: PlainDate = PlainDate.of(
        Calendar.getInstance(localeApp()).get(Calendar.YEAR),
        Calendar.getInstance(localeApp()).get(Calendar.MONTH) + 1,
        Calendar.getInstance(localeApp()).get(Calendar.DAY_OF_MONTH)
    )
```
Do you think it's better than other, because take a look as the deep source code, it's dont have any related with created time zone, just create PlainDate POJO. I just concern it will destroy the rule for other transform method like convert `plaindate` to `china calendar`.

**Comment by MenoData** [comment]
I have looked into the details of initialization and note one correction: The class `PlainDate` will always be prefetched, even if the boolean parameter in the initialization method is set to `false`. This is necesssary for a clean and stable set up of class loading of core classes. The consequence is for you:

You could even set the boolean parameter to `false`. If you nevertheless want the time zone data of Time4A to be prefetched then you could do:

```
public class MyApplication
    extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        ApplicationStarter.initialize(this, false);
        Runnable prefetch = new Runnable() {
                TZID tzid = Timezone.ofSystem().getID();
                Log.i("TIME4A", "System time zone at start: [" + tzid.canonical() + "]");
        };
        Executors.defaultThreadFactory().newThread(prefetch).start();
    }
}
```

Compared with the standard prefetch scenario, this initialization is shorter because prefetching the format engine is not performed.

--------------------------------------

About your code suggestion using `Calendar.getInstance()`:

Sure, the method `PlainDate.of(year, month, day)` performs very quickly because - after short parameter check - the inner state is set directly by given parameters. No time zone loading is involved. However, the call of `Calendar.getInstance()` still involves loading of time zone data, but not those of Time4A. Instead the time zone data of Android platform are used, so I would not expect any special progress compared with using `SystemClock.inPlatformView().today()`. I would rather try to avoid the mixture of old `Calendar`-class with Time4A whenever possible.

About your fear that the conversion of `PlainDate` to `ChineseCalendar` might be affected, no, this kind of conversion does not use time zone data of any kind. Time zone data come only into play if you want to get the CURRENT date.

By the way, I have also looked into the details of time zone loading. The whole thing is already well optimized. It loads the asset `tzdata.repository` (about 94 kByte) into a hash map (from tz-identifier to a byte-array). If a time zone is requested for a special identifier then the byte array (compact binary data) will be deserialized to a complex set of zone rules and will finally be cached. This is comparable to what for example `java.time` in OpenJDK does.

**Comment by kingvhit** [comment]
Thank you for the detailed information.
