### ISSUE TITLE
Upgrade Time4A to use latest version of Time4J

### ISSUE THREAD

**Issue by SaeedZhiany** [MenoData/Time4J#880]
your examples in this repository are based on V5.x but it seems Time4A uses V3.x of Time4J as you said [here](https://github.com/MenoData/Time4A#what-is-time4a)

**Comment by MenoData** [comment]
Well, the main development line is on Time4J and its master branch (v5.x). Time4A is a derivate specialized for Android and has used the former Time4J-branch v3.x. Time4A is still in (separate) development and overtakes some/many new features developed for Time4J where appropriate. However, Time4A cannot overtake every feature mainly because it is based on Java-6 while Time4J is based on Java-8 or later. For example, stream support and the range/interval-package only exist in Time4J, but not in Time4A.

**Comment by MenoData** [comment]
To be more clear: Time4A does not "use" Time4J, but just overtakes a selection of new Time4J-features on the API-Level of Java-6. So the upgrading is done in a different way than you might expect. Consequently, Time4A has no gradle-dependency on Time4J.

**Comment by SaeedZhiany** [comment]
Oh, Thank you for your clarification.
