### ISSUE TITLE
Using Local variant data for hijri Calendar

### ISSUE THREAD

**Issue by a5rar** [MenoData/Time4J#888]
Is it possible to maintain a local data source for HijriCalendar?  i.e. im expecting to be able to put islamic_umulqura.data in my  spring boot resources directory in a folder called data. but when i do this it doesnt look like its overriding the one in the base project.
What would be really nice is to be able to provide this data via a sql datasource, this will definately fit into common islamic practices of local moon sighting allowing each Country/Community to update there local variant data on a monthly basis, where umulqura data i guess is based entirely on Saudi Arabia moon sighting records which happen every other month and do not correlate to moonsightings in other parts of the world.

**Comment by MenoData** [comment]
Yes, it is possible but use a unique name for your variant because overriding existing names is not supported. The documentation of class `HijriCalendar` states:

> New variants can be configured by a file named "{variant-name}.data" in the data-subdirectory of resource class path (where hyphens are replaced by underscores). Format details see the file "islamic_umalqura.data".

So you could name your variant like "islamic-local" (where you should replace the term "local" by a more appropriate term) and then insert an ASCII-text file with the corresponding name "data/islamic_local.data" into your resource classpath. Of course, the content of this file needs to be customized, too, including the first line "type=islamic-local".

Following names are already preserved and - as far as I can see - cannot be overridden unless you find a way to give priority to your user-defined resource files in context of your classloader (which might need to be customized for this purpose):

- islamic-umalqura
- islamic-diyanet
- islamic-icu4j

IMHO, overriding should not be considered because it can be confusing for people expecting for example the calendar of Saudi-Arabia when they specify "islamic-umalqura" and getting another local variant instead.

------

About your second point using a SQL datasource, this is not yet implemented but sounds like an interesting enhancement. A first shot in the blue might look like introducing an extra interface:

```
public interface HijriData {
  String getCalendarType(); // example: "islamic-local"
  String getVersion(); // might be an incrementing update counter in sql-database
  int minHijriYear();
  int maxHijriYear();
  PlainDate gregorianFirstDay(); // first ever supported Hijri date as gregorian counterpart
  int[] getLengthOfMonths(int hijriYear); // array of 12 elements (for each month per year)
}
```

and then a new static registration method in the class `HijriCalendar` with the signature

`public static void register(HijriData data) {...}
`
which needs to be called before any other calendar usage in Time4J (best at server start).

A user-defined implementation of `getLengthOfMonths(int)` could look like accessing a SQL database table row with 13 integer columns (first column is the year, the other 12 stand for the months). The given parameter for the hijri year would then indicate a where-criterion to access the row.

How do you think about?

**Comment by a5rar** [comment]
Awesome.
**so on the first part the question bit?** 
I can confirm its working the bit i didin't realise is that the name of the variant and the file needs to be prefixed with islamic.  so the variant should be islamic-{custom-name}.data.  You are correct overriding existing calendars is not a good idea, i mentioned it as i though that it would be easy to override. The custom name solution is better.

**On the enhancement part**
The approach looks sensible. Atleast form a java perspective.  in a web application the register method can be part of the context initialization.    

I havent looked at how the register method can be integrated.  but doing that properly is probably the most critical part.

**Comment by MenoData** [comment]
Okay, so the first part is answered while we can see the second part as enhancement. Yes, caching the database query result is necessary otherwise we would get an explosion of sql-queries at every call. So the registration is obviously part of context initialization. Furthermore, I think it is sensible to do just one call to sql database and get one table of data which has to be fit into the `HijriData` scheme. Am actually not sure how to support this best in terms of API-interface. Any suggestions to improve the `HijriData`-interface?

**Comment by a5rar** [comment]
hi Sorry for the late response, I think the caching can and  should be dealt with by the implementation to the interface. That way if someone wants to report moon sighting for there local variant they can flush the cache. I might spend some time on the weekend to see what i can come up with, do you have any tips on how to add integration for the HijriData Interface

**Comment by MenoData** [comment]
Sorry I am also late, this time due to Corona crisis which leaves me with less time than ever (home schooling for my children).

I agree that caching should be the responsibility of the implementation of the interface. And I think the implementation should get an additional method

`public void refresh()`

which will be called as needed whenever the cache needs to be flushed or updated. For example, you can call `HijriCalendar.register(yourOwnLocalData)` and then call `refresh()` on your implementation in order to call the sql-database and to fill the cache inside your implementation.

**Comment by MenoData** [comment]
I hope my new interface `HijriData` is fine for you. It can easily be based on a SQL database table with 13 integer columns, first one for the Hijri year and the other 12 for the months (i.e. length of month).
