### ISSUE TITLE
Getting time of day when shadow length is equal to X

### ISSUE THREAD

**Issue by a5rar** [MenoData/Time4J#890]
Ive been playing around with the library for a few days now, and wondering if there is a way to get the time of day when the shadow of  object is at a particuar length.
SolarPosition can give me the shadow length at a particular time of the day but i want to be able to do the compute the other way around where we get the time based on the shadow length. 
I can do it using recursion but there must be a better way to do this.

**Comment by MenoData** [comment]
This is not yet implemented. Well, I am not sure if this is really a calendrical issue (probably rather interesting for criminalogy ;-)). Can you describe your use case?

Anyway, I don't think there is a better way than recursion or computing by nested intervals (my favourite) because the underlying astronomical formula cannot be easily "reversed" like multiplication versus division. Furthermore, they are mainly based on deducing and approximation from empirical data. After some brainstorming, my suggestion would be the introduction of following two new methods in the class `SolarTime`:

```
public ChronoFunction<CalendarDate,Optional<Moment>> timeOfShadowBeforeNoon(double objectHeight, double shadowLength());

public ChronoFunction<CalendarDate,Optional<Moment>> timeOfShadowAfterNoon(double objectHeight, double shadowLength());

```

**Comment by MenoData** [comment]
I have realized this feature with the small limitation that polar regions are not supported. Reason is that a) the calculations become overly complex because the movement of the sun is no longer strict monotonic and b) the precision of calculation suffers from shallow sun angles in general.
