### ISSUE TITLE
There are two time zones with a difference of two days.

### ISSUE THREAD

**Issue by mdorreh** [MenoData/Time4J#896]
Hi. I am working for a calendar startup that uses your library. We let the users select the timezones for their calendars. For example, one calendar's timezone can be UTC-14 and the other can be UTC+11. However, in this situation, if we assume that we are at 13:00 PM based on Greenwich on 13th April, then the first calendar shows date 23:00 PM on 12th April and the second calendar shows date 00:00 AM on 14th April. But as far as I know, only one day is allowed.

**Comment by MenoData** [comment]
The difference between UTC-14 and UTC+11 is 25 hours which is more than one full day. So it happens that - depending on the actual time - the related dates can differ from each other even by two calendar days instead of usually one calendar day.

**Concrete:** You refer to Greenwich time of 2020-04-13T13:00 (I assume here UTC+00). Then if you add 11 hours offset to get the local time for UTC+11 you will get 2020-04-14T00:00. And the other way for applying UTC-14 you have to subtract 14 hours and then you get as local time: 2020-04-12T23:00.

I don't see any failure or bug. All is fine.
