### ISSUE TITLE
How to format relative times between two moments?

### ISSUE THREAD

**Issue by mdorreh** [MenoData/Time4J#926]
Is there a feature to take two moments and format duration between these two moments and print appropriate output? 
For example, if the duration between the two moments is 1 week and 2 days prints  1 week and two days ago or 1 week and 2 days later (with respect to what moment appears at the first).  Or if the duration is 2 hours and 30 minutes prints 2 hours and 30 minutes ago or later.

**Comment by MenoData** [comment]
Relative times in ONE unit can be obtained by methods like [printRelativeInStdTimezone](http://time4j.net/javadoc-en/net/time4j/PrettyTime.html#printRelativeInStdTimezone-net.time4j.base.UnixTime-). All methods with prefix "printRelative" do this. Usually one of both moments is given by a clock. If you want to deviate from a running clock then you might use a reference clock with fixed time. Example:

```
      TimeSource<?> clock = () -> PlainTimestamp.of(2015, 6, 30, 23, 59, 54).atUTC();
      String remainingDurationInRealSeconds =
          PrettyTime.of(Locale.ENGLISH).withReferenceClock(clock).printRelative(
              PlainTimestamp.of(2015, 7, 1, 0, 0, 0).atUTC(),
              ZonalOffset.UTC);
      System.out.println(remainingDurationInRealSeconds); // in 7 seconds
```

Duration expressions spanning multiple units are not supported for relative times. In English, you have formatted representations of relative times using the words "in" or "ago". However, for any other duration expressions, you can have multiple units. Example:

```
    @Test
    public void print15Years3Months1Week2DaysUS() {
        Duration<?> duration =
            Duration.ofCalendarUnits(15, 3, 2).plus(1, WEEKS);
        assertThat(
            PrettyTime.of(Locale.US).print(duration),
            is("15 years, 3 months, 1 week, and 2 days"));
    }
```

If the duration is negative then you will observe negative numbers. Otherwise, the duration might be obtained the standard way to use between-expressions like:

```
        PlainTimestamp tsp1 = SystemClock.currentMoment().toLocalTimestamp();
        PlainTimestamp tsp2 = tsp1.plus(37, CalendarUnit.DAYS); // or use minus() for negative duration
        Duration<?> duration =
            Duration.in(Timezone.ofSystem(), CalendarUnit.MONTHS, CalendarUnit.DAYS)
                .between(tsp1, tsp2);
        String s = PrettyTime.of(Locale.ENGLISH).print(duration.abs()); // suppress negative signs
        if (duration.isNegative()) {
            s = s + " ago";
        } else {
            s = "in " + s;
        }
        System.out.println(s); // in 1 month and 6 days
```

The second example shows how to construct a relative time for more than one unit. By the way, the moments involved in the calculation must be transformed to local/zonal timestamps. **But I stress the point that this special solution can only be used for English.** Most other languages do not allow this approach. For example, German language also requires a different declination of unit names when constructing a relative time.

The real reason why this IMHO small limitation of relative times constrained to one unit only exists is simply the fact that the underlying localized text resources for duration unit expressions cannot be generalized. It is indeed a restriction set by CLDR data published by unicode org.

**Comment by mdorreh** [comment]
Thanks a lot for your consideration.
