### ISSUE TITLE
Is it possible to share library based on Time4J between JVM and Android applications?

### ISSUE THREAD

**Issue by mel4tonin4** [MenoData/Time4J#935]
Hello.

As far as I understand, if a module is based on Time4J, I can't share it between a JVM application and a Android application, because the latter would require Time4A.

Even if I link Time4A and initialize it in my Android application, I will get a long list of error of this kind:
```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class net.time4j.AbstractDateElement found in modules jetified-time4j-android-4.7-2020a-runtime (net.time4j:time4j-android:4.7-2020a) and jetified-time4j-base-5.7 (net.time4j:time4j-base:5.7)
```

Is this correct?

If this is correct, why is it so? Isn't it possible to separate the interface and the implementation of the classes which depend on the platform?

Thanks!

**Comment by MenoData** [comment]
Yes, you are right in saying that it is actually NOT possible to distribute Time4J also on Android platforms, or to distribute Time4A on JVM applications.

One important reason is that Time4J is compiled for Java 8+ onwards while Time4A is still runnable on very old Android platforms with just the minimum level 9. Therefore Time4A has no features depending on new Java features like streams or the new `java.time` api.

Another not less important reason is that the resource management is different on both platforms. For example, elder versions of Time4A (and Time4J) depend on the class `java.util.ResourceBundle`. But this was a big problem because the implementation of this class was significantly different on Android compared to JVM environments. So I had to replace it by another resource management architecture. Of course, I like the idea to have the same architecture on all platforms but must finally respect the fact that Android is simply not Java. There is unfortunately no guarantee that "interfaces" will be the same contract neither on Android or JVM.

Apps between Android and JVM-environments should share time data preferrably in ISO-8601-notation, not share themselves as distributable apps however (like RMI-based apps or similar). Here, we have to consider the fact that Time4J/A is mainly centered around immutable value types not business contracts/interfaces. Therefore the separation between API and implementations is much less important.

If you miss Java-8+ features in Time4A then it might be a good idea to develop a new Time4A main version derived from actual Time4J-master branch. However, for me as developer, this is a lot of migration and maintenance work. We should also not forget that still many Android installations are older than API-level 26.

**Comment by mel4tonin4** [comment]
Then, all things considered, I will probably do the following:

- use a new class for storing timestamps, which I'll be able to use on both Android and JVM of any version.
- create a interface for a service for performing computations based on this objects of this class and to format them to text
- implement this interface using Time4J on JVM and Time4A on Android.

Thanks for the answer and for the libraries, Meno!

**Comment by mel4tonin4** [comment]
Hello.

I was wondering if desugaring of Java8+ APIs on older Android has any impact on Time4A.

[Java 8 support](https://developer.android.com/studio/write/java8-support)

[Java 8 support table](https://developer.android.com/studio/write/java8-support-table)
