### ISSUE TITLE
Reduce library size by excluding for non english resources

### ISSUE THREAD

**Issue by ranjanrukhaya** [MenoData/Time4J#937]
This lib support multiple languages and include many resources for that but I just need to support only one language i.e "english".

Is there any way by which i can only get the resources required for "en" language and exclude others. This will help us in reducing app size.

**Comment by MenoData** [comment]
I have labelled this question with "time4a" because I think that such size requirements are irrelevant on standard Java platforms. So all the following statements refer only to the sister project Time4A.

**You can use the proguard tool to shrink your resources**.

More detailed documentation can be found on the [website of Android](https://developer.android.com/studio/build/shrink-code#shrink-resources). It is also possible to specify which resources you need to keep. If you plan to hold only the English resources then please also hold the root resources, for example: "net/time4j/i18n/names/iso8601.properties" and "net/time4j/i18n/names/iso8601_en.properties" and maybe also "net/time4j/i18n/names/iso8601_en_GB.properties" (for specializations in various English speaking countries) etc.

Eventually you also want to keep some text resources in the path "net/time4j/calendar/names/" for English (if you use other calendars than the gregorian one).

Disclaimer: I have not tested this way of resource shrinking. [Some people have reported](https://stackoverflow.com/questions/43838269/android-how-to-tell-shrinkresources-to-keep-certain-resources) that leaving out the file extensions might be necessary.

**Comment by MenoData** [comment]
Just now, I have released v4.8-2021a of Time4A. Please pay attention to the changed paths of some text resources.
