### ISSUE TITLE
TZID DisplayName Error (Korean Standard Time > Korea Standard Time)

### ISSUE THREAD

**Issue by safesoft-ysh** [MenoData/Time4J#971]
Below a code's result is 'Korean Standard Time'.

```
import net.time4j.tz.NameStyle;
import net.time4j.tz.TZID;
import net.time4j.tz.Timezone;

...

String winzone = "WINDOWS~Asia/Seoul";
NameStyle dummy = NameStyle.LONG_STANDARD_TIME; // does not really matter
String result = Timezone.of(winzone).getDisplayName(dummy, Locale.US);
System.out.println(result);
```

But, correct name of KST is 'Korea Standard Time'.
Please the check.
Thank you

**Comment by MenoData** [comment]
Thank you for your contribution and sorry for late reply. The name/description of Korean time zone originates from Java standard code using the class` java.text.DateFormatSymbols`. And this class fetches the text in question finally from unicode cldr repository. The actual content related to Korea can be found in:

[meta-zone-entry Korea](https://github.com/unicode-org/cldr/blob/747d5f16904bbe42d0aaf3fe4c5cc7049252642c/common/main/en.xml#L4070)

And yes, it yields the text "`Korean Standard Time`". We can certainly discuss why not "Korea Standard Time", but this discussion is out of scope of Time4J since this library is just a consumer of JDK-entries in this detail. Maybe you should send a request to the cldr group instead.
