### ISSUE TITLE
HijriCalendar.VARIANT_DIYANET stopped working

### ISSUE THREAD

**Issue by geekmentors** [MenoData/Time4J#976]
It stopped working as it is mentioned in the documentation 
"The supported range is 1318-01-01/1444-05-29 (ISO: 1900-05-01/2022-12-23)."

**Comment by MenoData** [comment]
Thank you very much for your good question. I have now looked at the original source of data and see that the website had been updated to incorporate data until western year 2028. See: https://webspace.science.uu.nl/~gent0113/islam/diyanetcalendar.htm

Do you know a better source (ideally a direct link to the data of diyanet ministry)? Maybe at: https://www.diyanet.gov.tr/tr-TR

**Comment by merve-esen** [comment]
I face the same issue on my Android app. Do I need open an issue on Time4A?

**Comment by MenoData** [comment]
@merve-esen This issue is the right place for the diyanet topic.

About Time4A, there is actually another problem rooted in the build structure. I need to update the build procedure from the scratch because the used service offered by Bintray had unfortunately been stopped. So I need new gradle scripts...

**Comment by merve-esen** [comment]
I'll wait or use another variant then. Thanks for the explanation.

**Comment by MenoData** [comment]
Nobody seems to know a direct source on the website of diyanet ministry so I think it is okay to continue using the data of dutch university.
